[package]
name = "volo_macro"
version = "0.1.0"
edition = "2021"
license = "SSPL-1.0"
description = "volo helper macro for any error"
homepage = "https://github.com/wactax/volo_macro"

[dependencies]
